services:
  wa-server:
    build:
      context: .
      dockerfile: ./wa-server/Dockerfile
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./auth_data:/app/wa-server/auth_data
    restart: unless-stopped
